name = "BlogRa"
license = "GPL"
licenselink = "https://github.com/rafed/BlogRa/blob/master/LICENSE"
description = "The Ultimate Tech Blogging Theme"
homepage = "https://github.com/rafed/BlogRa"
tags = ["blog", "responsive", "google analytics", "disqus", "google search", "bootstrap", "fast", "social media share", "code", "math equations", "seo", "mermaid diagrams", "tech"]
min_version = "0.91.2"

[author]
  name = "Rafed Muhammad Yasir"
  homepage = "https://rafed.github.io/"